version: '3.4'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    networks:
      - db-local
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5

  librarysystem:
    image: ${DOCKER_REGISTRY-}librarysystem
    container_name: librarysystem
    build:
      context: ./LibrarySystem
      dockerfile: Dockerfile
    depends_on:
      - reservation
      - library
      - rating
    networks:
      - reservation-local
      - library-local
      - rating-local
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/manage/health"]
      interval: 5s
      timeout: 10s

  reservation:
    image: ${DOCKER_REGISTRY-}reservation
    container_name: reservation
    build:
      context: ./Reservation
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - reservation-local
      - db-local
    ports:
      - "8070:8070"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8070/manage/health"]
      interval: 5s
      timeout: 10s

  library:
    image: ${DOCKER_REGISTRY-}library
    container_name: library
    build:
      context: ./Library
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - library-local
      - db-local
    ports:
      - "8060:8060"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8060/manage/health"]
      interval: 5s
      timeout: 10s

  rating:
    image: ${DOCKER_REGISTRY-}rating
    container_name: rating
    build:
      context: ./Rating
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - rating-local
      - db-local
    ports:
      - "8050:8050"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8050/manage/health"]
      interval: 5s
      timeout: 10s

volumes:
  db-data:

networks:
  reservation-local:
  library-local:
  rating-local:
  db-local:
    driver: bridge